**Текст, выделенный полужирным шрифтом**## 🐱 [1] Клонируем репозиторий курса в Colab

# 📊 Week 2: Data Analysis — Чтение и проверка данных

**Цель:** Научиться читать CSV-файл из репозитория GitHub в Google Colab и выполнять базовую проверку данных с помощью pandas.

**Данные:**

- `countries_government_development.csv` — страны, форма правления, индекс человеческого развития, ВВП на душу населения и континент из Wikidata.
- `population.csv` — население стран по годам из Wikidata.

**Что мы делаем:**

1. Клонируем репозиторий GitHub в Colab.
2. Читаем CSV-файл в pandas DataFrame.
3. Переименовываем столбцы.
4. Проверяем структуру данных.
5. Проверяем пропущенные значения.
6. Смотрим базовую статистику по числовым столбцам.

In [ ]:
# подключаем библиотеку для работы с таблицами
import pandas as pd

In [ ]:
# удаляем старую копию репозитория, если она уже была загружена
!rm -rf python-ai-surkoa-olga

# клонируем репозиторий из github
!git clone https://github.com/surkovaolga2005-png/python-ai-surkoa-olga

Cloning into 'python-ai-surkoa-olga'...
remote: Enumerating objects: 380, done.
remote: Counting objects: 100% (175/175), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 380 (delta 154), reused 111 (delta 111), pack-reused 205 (from 2)
Receiving objects: 100% (380/380), 2.60 MiB | 8.49 MiB/s, done.
Resolving deltas: 100% (216/216), done.

In [ ]:
# читаем основной csv-файл из папки data
file_path = "python-ai-surkoa-olga/data/countries_government_development.csv"

df = pd.read_csv(file_path)

df.head()

,country,countryLabel,governmentLabel,hdi,gdpPerCapita,continentLabel
0,http://www.wikidata.org/entity/Q139656941,Q139656941,монархия,NaN,NaN,NaN
1,http://www.wikidata.org/entity/Q408,Австралия,конституционная монархия,0.951,54348.23,Австралия и Океания
2,http://www.wikidata.org/entity/Q408,Австралия,федеративное государство,0.951,54348.23,Австралия и Океания
3,http://www.wikidata.org/entity/Q408,Австралия,представительная демократия,0.951,54348.23,Австралия и Океания
4,http://www.wikidata.org/entity/Q40,Австрия,республика,0.916,NaN,Европа

In [ ]:
# переименовываем столбцы основного файла
df = df.rename(columns={
    "country": "country_id",
    "countryLabel": "country",
    "governmentLabel": "form_of_government",
    "hdi": "human_development_index",
    "gdpPerCapita": "gdp_per_capita",
    "continentLabel": "continent"
})

# приводим числовые столбцы к числовому типу
df["human_development_index"] = pd.to_numeric(df["human_development_index"], errors="coerce")
df["gdp_per_capita"] = pd.to_numeric(df["gdp_per_capita"], errors="coerce")

df.head()

,country_id,country,form_of_government,human_development_index,gdp_per_capita,continent
0,http://www.wikidata.org/entity/Q139656941,Q139656941,монархия,NaN,NaN,NaN
1,http://www.wikidata.org/entity/Q408,Австралия,конституционная монархия,0.951,54348.23,Австралия и Океания
2,http://www.wikidata.org/entity/Q408,Австралия,федеративное государство,0.951,54348.23,Австралия и Океания
3,http://www.wikidata.org/entity/Q408,Австралия,представительная демократия,0.951,54348.23,Австралия и Океания
4,http://www.wikidata.org/entity/Q40,Австрия,республика,0.916,NaN,Европа

In [ ]:
# создаем таблицу без повторов стран
df_unique = df.drop_duplicates(subset=["country_id"])

# сравниваем количество строк до и после удаления дублей
print("строк в исходной таблице:", df.shape[0])
print("уникальных стран:", df_unique.shape[0])
print("количество удаленных дублей:", df.shape[0] - df_unique.shape[0])

строк в исходной таблице: 329
уникальных стран: 210
количество удаленных дублей: 119

In [ ]:
# проверяем заполненность optional-полей
print("доля стран с известным hdi:", df_unique["human_development_index"].notna().mean().round(2))
print("доля стран с известным ввп на душу населения:", df_unique["gdp_per_capita"].notna().mean().round(2))
print("доля стран с известным континентом:", df_unique["continent"].notna().mean().round(2))

доля стран с известным hdi: 0.92
доля стран с известным ввп на душу населения: 0.04
доля стран с известным континентом: 0.99

In [ ]:
# смотрим информацию по таблице с уникальными странами
df_unique.info()

<class 'pandas.core.frame.DataFrame'>
Index: 210 entries, 0 to 328
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country_id               210 non-null    object
 1   country                  210 non-null    object
 2   form_of_government       166 non-null    object
 3   human_development_index  193 non-null    float64
 4   gdp_per_capita           9 non-null      float64
 5   continent                207 non-null    object
dtypes: float64(2), object(4)
memory usage: 11.5+ KB

In [ ]:
# читаем отдельный csv-файл с населением по годам
population_path = "python-ai-surkoa-olga/data/population.csv"

population_df = pd.read_csv(population_path)

population_df.head()

,country,countryLabel,population,pointInTime,year
0,http://www.wikidata.org/entity/Q408,Австралия,22637127,2012-03-01T00:00:00Z,2012.0
1,http://www.wikidata.org/entity/Q408,Австралия,22920450,2012-12-01T00:00:00Z,2012.0
2,http://www.wikidata.org/entity/Q408,Австралия,22826041,2012-09-01T00:00:00Z,2012.0
3,http://www.wikidata.org/entity/Q408,Австралия,22723904,2012-06-01T00:00:00Z,2012.0
4,http://www.wikidata.org/entity/Q408,Австралия,23035199,2013-03-01T00:00:00Z,2013.0

In [ ]:
# проверяем размер таблицы с населением
print("количество строк:", population_df.shape[0])
print("количество столбцов:", population_df.shape[1])

количество строк: 10222
количество столбцов: 5

In [ ]:
# переименовываем столбцы в таблице с населением
population_df = population_df.rename(columns={
    "country": "country_id",
    "countryLabel": "country",
    "population": "population",
    "pointInTime": "point_in_time",
    "year": "year"
})

population_df.head()

,country_id,country,population,point_in_time,year
0,http://www.wikidata.org/entity/Q408,Австралия,22637127,2012-03-01T00:00:00Z,2012.0
1,http://www.wikidata.org/entity/Q408,Австралия,22920450,2012-12-01T00:00:00Z,2012.0
2,http://www.wikidata.org/entity/Q408,Австралия,22826041,2012-09-01T00:00:00Z,2012.0
3,http://www.wikidata.org/entity/Q408,Австралия,22723904,2012-06-01T00:00:00Z,2012.0
4,http://www.wikidata.org/entity/Q408,Австралия,23035199,2013-03-01T00:00:00Z,2013.0

In [ ]:
# приводим население и год к числовому типу
population_df["population"] = pd.to_numeric(population_df["population"], errors="coerce")
population_df["year"] = pd.to_numeric(population_df["year"], errors="coerce")

population_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10222 entries, 0 to 10221
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country_id     10222 non-null  object
 1   country        10222 non-null  object
 2   population     10222 non-null  int64
 3   point_in_time  10220 non-null  object
 4   year           10220 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 399.4+ KB

In [ ]:
# проверяем пропуски в таблице с населением
population_df.isna().sum()

country_id       0
country          0
population       0
point_in_time    2
year             2
dtype: int64

In [ ]:
# удаляем строки без года и населения
population_clean = population_df.dropna(subset=["year", "population"]).copy()

# переводим год в целое число
population_clean["year"] = population_clean["year"].astype(int)

population_clean.head()

,country_id,country,population,point_in_time,year
0,http://www.wikidata.org/entity/Q408,Австралия,22637127,2012-03-01T00:00:00Z,2012
1,http://www.wikidata.org/entity/Q408,Австралия,22920450,2012-12-01T00:00:00Z,2012
2,http://www.wikidata.org/entity/Q408,Австралия,22826041,2012-09-01T00:00:00Z,2012
3,http://www.wikidata.org/entity/Q408,Австралия,22723904,2012-06-01T00:00:00Z,2012
4,http://www.wikidata.org/entity/Q408,Австралия,23035199,2013-03-01T00:00:00Z,2013

In [ ]:
# агрегируем население, чтобы для одной страны и одного года была одна строка
pop_yearly = (
    population_clean
    .groupby(["country_id", "country", "year"], as_index=False)["population"]
    .max()
)

pop_yearly.head()

                             country_id country  year  population
0  http://www.wikidata.org/entity/Q1000   Габон  1960      498823
1  http://www.wikidata.org/entity/Q1000   Габон  1961      503762
2  http://www.wikidata.org/entity/Q1000   Габон  1962      509348
3  http://www.wikidata.org/entity/Q1000   Габон  1963      515762
4  http://www.wikidata.org/entity/Q1000   Габон  1964      523236

In [ ]:
# проверяем размер таблицы после агрегации
print("строк до агрегации:", population_clean.shape[0])
print("строк после агрегации:", pop_yearly.shape[0])
print("количество стран:", pop_yearly["country_id"].nunique())
print("минимальный год:", pop_yearly["year"].min())
print("максимальный год:", pop_yearly["year"].max())

строк до агрегации: 10220
строк после агрегации: 9872
количество стран: 207
минимальный год: 1605
максимальный год: 2026

In [ ]:
# смотрим статистику по агрегированным данным населения
pop_yearly[["population", "year"]].describe()

         population         year
count  9.872000e+03  9872.000000
mean   2.299565e+07  1983.918254
std    8.937385e+07    35.567226
min    2.800000e+01  1605.000000
25%    6.629365e+05  1972.000000
50%    5.064862e+06  1988.000000
75%    1.599161e+07  2004.000000
max    1.443497e+09  2026.000000

## Вывод

Во второй части задания были загружены два CSV-файла из папки data.

Первый файл, countries_government_development.csv, содержит сведения о странах: идентификатор страны в Wikidata, название страны, форму правления, индекс человеческого развития, ВВП на душу населения и континент.

Так как одна страна может иметь несколько форм правления, для анализа числовых показателей была создана отдельная таблица df_unique, где каждая страна учитывается один раз. Это нужно, чтобы статистика по HDI, ВВП на душу населения и континентам не искажалась дублями.

Также была проверена заполненность OPTIONAL-полей: HDI, ВВП на душу населения и континент. Было видно, что показатель ВВП на душу населения заполнен слабо, поэтому его нужно использовать осторожно при дальнейшей визуализации.

Второй файл, population.csv, содержит значения населения стран по годам. Так как в Wikidata у одной страны за один год может быть несколько записей, была создана агрегированная таблица pop_yearly. В ней для каждой страны и каждого года оставлено одно значение населения.

После очистки данные подходят для дальнейшего анализа и визуализации в week3_visualization.ipynb.