<a href="https://colab.research.google.com/github/surkovaolga2005-png/python-ai-surkoa-olga/blob/main/notebooks/week2b_read_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Текст, выделенный полужирным шрифтом**## 🐱 [1] Клонируем репозиторий курса в Colab

# 📊 Week 2: Data Analysis — Чтение и проверка данных

**Цель:** Научиться читать CSV-файл из репозитория GitHub в Google Colab и выполнять базовую проверку данных с помощью pandas.

**Данные:**

- `countries_government_development.csv` — страны, форма правления, индекс человеческого развития, ВВП на душу населения и континент из Wikidata.
- `population.csv` — население стран по годам из Wikidata.

**Что мы делаем:**

1. Клонируем репозиторий GitHub в Colab.
2. Читаем CSV-файл в pandas DataFrame.
3. Переименовываем столбцы.
4. Проверяем структуру данных.
5. Проверяем пропущенные значения.
6. Смотрим базовую статистику по числовым столбцам.

In [ ]:
# подключаем pandas для работы с таблицами
import pandas as pd

In [ ]:
# удаляем старую копию репозитория, если она уже была загружена
!rm -rf python-ai-surkoa-olga

# клонируем репозиторий из github
!git clone https://github.com/surkovaolga2005-png/python-ai-surkoa-olga

Cloning into 'python-ai-surkoa-olga'...
remote: Enumerating objects: 365, done.
remote: Counting objects: 100% (191/191), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 365 (delta 159), reused 110 (delta 110), pack-reused 174 (from 1)
Receiving objects: 100% (365/365), 2.19 MiB | 17.42 MiB/s, done.
Resolving deltas: 100% (209/209), done.

In [ ]:
# подключаем pandas для работы с таблицами
import pandas as pd

In [ ]:
# переименовываем столбцы основного файла
df = df.rename(columns={
    "country": "country_id",
    "countryLabel": "country",
    "governmentLabel": "form_of_government",
    "hdi": "human_development_index",
    "gdpPerCapita": "gdp_per_capita",
    "continentLabel": "continent"
})

df.head()

,country_id,country_id,form_of_government,human_development_index,gdp_per_capita,continent
0,http://www.wikidata.org/entity/Q139656941,Q139656941,монархия,NaN,NaN,NaN
1,http://www.wikidata.org/entity/Q408,Австралия,конституционная монархия,0.951,54348.23,Австралия и Океания
2,http://www.wikidata.org/entity/Q408,Австралия,федеративное государство,0.951,54348.23,Австралия и Океания
3,http://www.wikidata.org/entity/Q408,Австралия,представительная демократия,0.951,54348.23,Австралия и Океания
4,http://www.wikidata.org/entity/Q40,Австрия,республика,0.916,NaN,Европа

In [ ]:
# читаем основной csv-файл из папки data
file_path = "python-ai-surkoa-olga/data/countries_government_development.csv"

df = pd.read_csv(file_path)

df.head()

,country,countryLabel,governmentLabel,hdi,gdpPerCapita,continentLabel
0,http://www.wikidata.org/entity/Q139656941,Q139656941,монархия,NaN,NaN,NaN
1,http://www.wikidata.org/entity/Q408,Австралия,конституционная монархия,0.951,54348.23,Австралия и Океания
2,http://www.wikidata.org/entity/Q408,Австралия,федеративное государство,0.951,54348.23,Австралия и Океания
3,http://www.wikidata.org/entity/Q408,Австралия,представительная демократия,0.951,54348.23,Австралия и Океания
4,http://www.wikidata.org/entity/Q40,Австрия,республика,0.916,NaN,Европа

In [ ]:
# переименовываем столбцы основного файла
df = df.rename(columns={
    "country": "country_id",
    "countryLabel": "country",
    "governmentLabel": "form_of_government",
    "hdi": "human_development_index",
    "gdpPerCapita": "gdp_per_capita",
    "continentLabel": "continent"
})

df.head()

,country_id,country,form_of_government,human_development_index,gdp_per_capita,continent
0,http://www.wikidata.org/entity/Q139656941,Q139656941,монархия,NaN,NaN,NaN
1,http://www.wikidata.org/entity/Q408,Австралия,конституционная монархия,0.951,54348.23,Австралия и Океания
2,http://www.wikidata.org/entity/Q408,Австралия,федеративное государство,0.951,54348.23,Австралия и Океания
3,http://www.wikidata.org/entity/Q408,Австралия,представительная демократия,0.951,54348.23,Австралия и Океания
4,http://www.wikidata.org/entity/Q40,Австрия,республика,0.916,NaN,Европа

In [ ]:
# читаем отдельный csv-файл с населением по годам
population_path = "python-ai-surkoa-olga/data/population.csv"

population_df = pd.read_csv(population_path)

population_df.head()

,country,countryLabel,population,pointInTime,year
0,http://www.wikidata.org/entity/Q408,Австралия,22637127,2012-03-01T00:00:00Z,2012.0
1,http://www.wikidata.org/entity/Q408,Австралия,22920450,2012-12-01T00:00:00Z,2012.0
2,http://www.wikidata.org/entity/Q408,Австралия,22826041,2012-09-01T00:00:00Z,2012.0
3,http://www.wikidata.org/entity/Q408,Австралия,22723904,2012-06-01T00:00:00Z,2012.0
4,http://www.wikidata.org/entity/Q408,Австралия,23035199,2013-03-01T00:00:00Z,2013.0

In [ ]:
# проверяем размер таблицы с населением
print("количество строк:", population_df.shape[0])
print("количество столбцов:", population_df.shape[1])

количество строк: 10222
количество столбцов: 5

In [ ]:
# переименовываем столбцы в таблице с населением
population_df = population_df.rename(columns={
    "country": "country_id",
    "countryLabel": "country",
    "population": "population",
    "pointInTime": "point_in_time",
    "year": "year"
})

population_df.head()

,country_id,country,population,point_in_time,year
0,http://www.wikidata.org/entity/Q408,Австралия,22637127,2012-03-01T00:00:00Z,2012.0
1,http://www.wikidata.org/entity/Q408,Австралия,22920450,2012-12-01T00:00:00Z,2012.0
2,http://www.wikidata.org/entity/Q408,Австралия,22826041,2012-09-01T00:00:00Z,2012.0
3,http://www.wikidata.org/entity/Q408,Австралия,22723904,2012-06-01T00:00:00Z,2012.0
4,http://www.wikidata.org/entity/Q408,Австралия,23035199,2013-03-01T00:00:00Z,2013.0

In [ ]:
# приводим население и год к числовому типу
population_df["population"] = pd.to_numeric(population_df["population"], errors="coerce")
population_df["year"] = pd.to_numeric(population_df["year"], errors="coerce")

population_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10222 entries, 0 to 10221
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country_id     10222 non-null  object
 1   country        10222 non-null  object
 2   population     10222 non-null  int64
 3   point_in_time  10220 non-null  object
 4   year           10220 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 399.4+ KB

In [ ]:
# проверяем пропуски в таблице с населением
population_df.isna().sum()

country_id       0
country          0
population       0
point_in_time    2
year             2
dtype: int64

In [ ]:
# смотрим статистику по населению и годам
population_df[["population", "year"]].describe()

         population          year
count  1.022200e+04  10220.000000
mean   2.349698e+07   1984.280724
std    8.906922e+07     35.435591
min    2.800000e+01   1605.000000
25%    7.116548e+05   1972.000000
50%    5.363458e+06   1989.000000
75%    1.738895e+07   2004.000000
max    1.443497e+09   2026.000000

In [ ]:
# приводим числовые столбцы основного файла к числовому типу
df["human_development_index"] = pd.to_numeric(df["human_development_index"], errors="coerce")
df["gdp_per_capita"] = pd.to_numeric(df["gdp_per_capita"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country_id               329 non-null    object
 1   country                  329 non-null    object
 2   form_of_government       281 non-null    object
 3   human_development_index  299 non-null    float64
 4   gdp_per_capita           12 non-null     float64
 5   continent                326 non-null    object
dtypes: float64(2), object(4)
memory usage: 15.6+ KB

## Вывод

Во второй части задания были загружены два CSV-файла из папки `data`.

Первый файл, `countries_government_development.csv`, содержит основные сведения о странах: идентификатор страны в Wikidata, название страны, форму правления, индекс человеческого развития, ВВП на душу населения и континент.

Второй файл, `population.csv`, содержит значения населения стран по годам. Этот файл вынесен отдельно, потому что у свойства `population` в Wikidata может быть несколько значений для одной страны, относящихся к разным годам.

С помощью pandas были проверены первые строки, размер таблиц, названия столбцов, типы данных, пропущенные значения и базовая статистика. Данные подходят для дальнейшего анализа и визуализации.